version: 1.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: AzureAppServiceZipDeploy
  appservice_environment: false
  website: darth-veyor-101
  username: $darth-veyor-101
  password:
    secure: VYEjjKlzz9psfI6g5mgnYTPpT56VmvHK8zutg2yVV16txsHz1/whQ4jDxOxWqnEM9Pc78GJmRfM4f5igtmO/4A==
  async_deploy: true
  retry_attempts: 3
  on:
    branch: master