version: 1.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
configuration: Release
cache:
  - packages -> **\packages.config
environment:
  slack_message_id: ''
  slack_channel_id: ''
before_build:
- cmd: nuget restore
- ps: .\Slackmessage.ps1 -mode 'post' -token $env:SLACK_API_TOKEN
build:
  publish_wap: true
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: Environment
  name: DEV Darth Veyor
  on:
    branch: master
on_success: 
- ps: .\Slackmessage.ps1 -mode 'update' -token $env:SLACK_API_TOKEN