version: 1.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: Environment
  name: DEV Darth Veyor
  on:
    branch: master